/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import core.KJV;
import java.util.*;
import javax.swing.JOptionPane;
import core.*;
import java.awt.BorderLayout;
import java.awt.DisplayMode;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import javax.swing.JFrame;
/**
 *
 * @author giovanni
 */
public class KJVGUI extends javax.swing.JFrame {

    private ArrayList<String> readThis = new ArrayList<String>();
    private HashMap<String, String> chapters = new HashMap<>();
    private HashMap<String, HashMap> theKJV = new HashMap<>();
    private HashMap<String, List> index = new HashMap<>();
    private String verseSelected = "";
    Integer chapterNo; 
    Integer chapterDifference;
    int fontSize = 12;
    HashMap<String, String> properNamesReversed = new HashMap<>();
   
    /**
     * Creates new form KJVGUI
     */
    public KJVGUI() {
        initComponents();


    }
    
    private void setProperNames()
    {
        HashMap<String, String> properNames = Coordinator.getBibleMapProperNames();      
        Set<String> namesReversed = properNames.keySet();
        for (String key : namesReversed)
        {
            properNamesReversed.put(properNames.get(key), key);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        verseWindow2 = new javax.swing.JScrollPane();
        verseWindow3 = new javax.swing.JTextArea();
        read_button = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayBook = new javax.swing.JTextArea();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        verses = new javax.swing.JScrollPane();
        verseWindow = new javax.swing.JTextArea();
        read_for_kids = new javax.swing.JButton();
        big_letters = new javax.swing.JButton();
        small_letters = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        bibleList = new javax.swing.JComboBox<>();
        read_book = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        read_chapter = new javax.swing.JButton();
        chapter = new javax.swing.JComboBox<>();
        read_previous_chapter = new javax.swing.JButton();
        read_next_chapter = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        read_verse = new javax.swing.JButton();
        verseNumbers = new javax.swing.JComboBox<>();
        read_button1 = new javax.swing.JButton();
        read_button5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        search_button = new javax.swing.JButton();
        search_word = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jInternalFrame4 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );

        jFrame1.setVisible(false);
        jFrame1.setMinimumSize(new java.awt.Dimension(1000, 680));

        verseWindow3.setColumns(20);
        verseWindow3.setFont(new java.awt.Font("Dialog", 0, 200)); // NOI18N
        verseWindow3.setRows(5);
        verseWindow2.setViewportView(verseWindow3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(verseWindow2, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(verseWindow2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        read_button.setText("Read");
        read_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jInternalFrame3.setVisible(true);

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBar(null);

        displayBook.setColumns(20);
        displayBook.setLineWrap(true);
        displayBook.setRows(5);
        displayBook.setWrapStyleWord(true);
        displayBook.setAlignmentX(1.0F);
        displayBook.setAlignmentY(1.0F);
        displayBook.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        displayBook.setMinimumSize(new java.awt.Dimension(0, 0));
        jScrollPane1.setViewportView(displayBook);
        displayBook.setCaretPosition(0);

        jInternalFrame2.setVisible(false);

        verseWindow.setColumns(20);
        verseWindow.setRows(5);
        verses.setViewportView(verseWindow);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(verses, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(verses, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        read_for_kids.setText("Big Screen ");
        read_for_kids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read_for_kidsActionPerformed(evt);
            }
        });

        big_letters.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        big_letters.setText("Big");
        big_letters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                big_lettersActionPerformed(evt);
            }
        });

        small_letters.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        small_letters.setText("Small");
        small_letters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                small_lettersActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Book of", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 48))); // NOI18N

        bibleList.setEditable(true);
        bibleList.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        bibleList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));
        HashMap<Integer, String> books = Coordinator.getProperBibleNames();
        HashMap<String, HashMap> properAndFileName = new HashMap<>();

        Set<Integer> properNames = books.keySet();
        for (Integer key : properNames)
        {
            bibleList.addItem(books.get(key));
        }

        //bibleList.setSelectedIndex(0);
        bibleList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bibleListActionPerformed(evt);
            }
        });

        read_book.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        read_book.setText("Read Book");
        read_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read_bookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bibleList, 0, 0, Short.MAX_VALUE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(read_book, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(bibleList, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(read_book, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Chapter", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 48))); // NOI18N

        read_chapter.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        read_chapter.setText("Read");
        read_chapter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read_chapterActionPerformed(evt);
            }
        });

        chapter.setEditable(true);
        chapter.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        chapter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        String fileName = "01_Genesis.txt";
        HashMap<String, HashMap> theBible = Coordinator.getTheBible();
        HashMap<Integer, List> theChapters = theBible.get(fileName);
        Set<Integer> keys = theChapters.keySet();
        int numberOfChapters = keys.size();
        for (int i = 1; i<=numberOfChapters; i++)
        {
            chapter.addItem(Integer.toString(i));
        }
        chapter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chapterActionPerformed(evt);
            }
        });

        read_previous_chapter.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        read_previous_chapter.setText("BACK");
        read_previous_chapter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read_previous_chapterActionPerformed(evt);
            }
        });

        read_next_chapter.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        read_next_chapter.setText("NEXT");
        read_next_chapter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read_next_chapterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(read_previous_chapter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chapter, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(read_chapter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(read_next_chapter)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(read_chapter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chapter, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(read_previous_chapter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(read_next_chapter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Verse", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 48))); // NOI18N

        read_verse.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        read_verse.setText("Read");
        read_verse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read_verseActionPerformed(evt);
            }
        });

        verseNumbers.setEditable(true);
        verseNumbers.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        verseNumbers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        String fv = "01_Genesis.txt";

        Integer chosenChapter = 1;
        List<String> verses = theChapters.get(chosenChapter);
        int numberOfVerses = verses.size();
        for (int i = 1; i<=numberOfVerses; i++)
        {
            verseNumbers.addItem(Integer.toString(i));
        }
        verseNumbers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verseNumbersMouseClicked(evt);
            }
        });
        verseNumbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verseNumbersActionPerformed(evt);
            }
        });

        read_button1.setText("Next");
        read_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read_button1ActionPerformed(evt);
            }
        });

        read_button5.setText("Back");
        read_button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read_button5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(read_button5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verseNumbers, 0, 126, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(read_verse, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(read_button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(read_verse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verseNumbers, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(read_button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(read_button5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Search"));

        search_button.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        search_button.setText("Search");
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });

        search_word.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(search_button, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
            .addComponent(search_word)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(search_word, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_button)
                .addGap(10, 10, 10))
        );

        jButton3.setText("Index Build");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Add to Favorites");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Letters");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jInternalFrame4.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 200)); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton6.setText("NEXT");

        javax.swing.GroupLayout jInternalFrame4Layout = new javax.swing.GroupLayout(jInternalFrame4.getContentPane());
        jInternalFrame4.getContentPane().setLayout(jInternalFrame4Layout);
        jInternalFrame4Layout.setHorizontalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame4Layout.setVerticalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Home");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Search");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("View");

        jMenuItem2.setText("Favorites");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(big_letters, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(small_letters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton5)
                                        .addComponent(jButton3)))
                                .addContainerGap(202, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(read_for_kids, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(big_letters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jButton5)))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(read_for_kids, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(38, 38, 38)
                                .addComponent(jButton3)
                                .addGap(33, 33, 33)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(small_letters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bibleListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bibleListActionPerformed
        // TODO add your handling code here:
        displayBook.setText("");
        chapter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        HashMap<String, String> properNames = Coordinator.getBibleMapProperNames();
        String fileName = properNames.get(bibleList.getSelectedItem().toString());
        HashMap<String, HashMap> theBible = Coordinator.getTheBible();
        HashMap<Integer, List> theChapters = theBible.get(fileName);
        Set<Integer> keys = theChapters.keySet();
        int numberOfChapters = keys.size();
        for (int i = 1; i<=numberOfChapters; i++)
        {
            chapter.addItem(Integer.toString(i));
        }
        
        
        
 
    }//GEN-LAST:event_bibleListActionPerformed

    private void read_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read_buttonActionPerformed
        // TODO add your handling code here:
         


 
  
        
        


        
    }//GEN-LAST:event_read_buttonActionPerformed

    private void read_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read_button1ActionPerformed
        // TODO add your handling code here:
               displayBook.setText("");
        HashMap<String, String> properNames = Coordinator.getBibleMapProperNames();
        String fileName = properNames.get(bibleList.getSelectedItem().toString());
        HashMap<String, HashMap> theBible = Coordinator.getTheBible();
        HashMap<Integer, List> theChapters = theBible.get(fileName);
        Set<Integer> keys = theChapters.keySet();
        Integer chosenChapter = Integer.parseInt(chapter.getSelectedItem().toString());
        List<String> verses = theChapters.get(chosenChapter);
        int numberOfVerses = verses.size();
        int verseNumber = Integer.parseInt(verseNumbers.getSelectedItem().toString())+1;
        verseNumbers.setSelectedItem(verseNumber);
        String selectedVerse = verses.get(verseNumber-1);
        displayBook.append(selectedVerse+"\n\n");
        displayBook.setCaretPosition(0);
    }//GEN-LAST:event_read_button1ActionPerformed

    private void read_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read_bookActionPerformed
        // TODO add your handling code here:
        displayBook.setText("");
        HashMap<String, String> properNames = Coordinator.getBibleMapProperNames();
        String fileName = properNames.get(bibleList.getSelectedItem().toString());
        HashMap<String, HashMap> theBible = Coordinator.getTheBible();
        HashMap<Integer, List> theChapters = theBible.get(fileName);
        Set<Integer> keys = theChapters.keySet();
        for (int c=1; c<=theChapters.size(); c++)
        {
            Integer chosenChapter = c;
            List<String> verses = theChapters.get(chosenChapter);
            for(String verse : verses)
            {
                displayBook.append(verse+"\n\n");
                
            } 
        }
        displayBook.setCaretPosition(0);
    }//GEN-LAST:event_read_bookActionPerformed

    private void read_previous_chapterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read_previous_chapterActionPerformed
        // TODO add your handling code here:
               displayBook.setText("");
        HashMap<String, String> properNames = Coordinator.getBibleMapProperNames();
        String fileName = properNames.get(bibleList.getSelectedItem().toString());
        HashMap<String, HashMap> theBible = Coordinator.getTheBible();
        HashMap<Integer, List> theChapters = theBible.get(fileName);
        Set<Integer> keys = theChapters.keySet();
        Integer chosenChapter = Integer.parseInt(chapter.getSelectedItem().toString())-1;
        chapter.setSelectedItem(chosenChapter);
        List<String> verses = theChapters.get(chosenChapter);
        int numberOfVerses = verses.size();
        for(String verse : verses)
            {
                displayBook.append(verse+"\n\n");
                
            } 
        displayBook.setCaretPosition(0);
        

        
    }//GEN-LAST:event_read_previous_chapterActionPerformed

    private void read_next_chapterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read_next_chapterActionPerformed
        // TODO add your handling code here:
               displayBook.setText("");
        HashMap<String, String> properNames = Coordinator.getBibleMapProperNames();
        String fileName = properNames.get(bibleList.getSelectedItem().toString());
        HashMap<String, HashMap> theBible = Coordinator.getTheBible();
        HashMap<Integer, List> theChapters = theBible.get(fileName);
        Set<Integer> keys = theChapters.keySet();
        Integer chosenChapter = Integer.parseInt(chapter.getSelectedItem().toString())+1;
        chapter.setSelectedItem(chosenChapter);
        List<String> verses = theChapters.get(chosenChapter);
        int numberOfVerses = verses.size();
        for(String verse : verses)
            {
                displayBook.append(verse+"\n\n");
                
            } 
        displayBook.setCaretPosition(0);
        


    }//GEN-LAST:event_read_next_chapterActionPerformed

    private void read_button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read_button5ActionPerformed
        // TODO add your handling code here:
                      displayBook.setText("");
        HashMap<String, String> properNames = Coordinator.getBibleMapProperNames();
        String fileName = properNames.get(bibleList.getSelectedItem().toString());
        HashMap<String, HashMap> theBible = Coordinator.getTheBible();
        HashMap<Integer, List> theChapters = theBible.get(fileName);
        Set<Integer> keys = theChapters.keySet();
        Integer chosenChapter = Integer.parseInt(chapter.getSelectedItem().toString());
        List<String> verses = theChapters.get(chosenChapter);
        int numberOfVerses = verses.size();
        int verseNumber = Integer.parseInt(verseNumbers.getSelectedItem().toString())-1;
        verseNumbers.setSelectedItem(verseNumber);
        String selectedVerse = verses.get(verseNumber-1);
        displayBook.append(selectedVerse+"\n\n");
        displayBook.setCaretPosition(0);
    }//GEN-LAST:event_read_button5ActionPerformed

    private void read_verseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read_verseActionPerformed
        // TODO add your handling code here:
        displayBook.setText("");
        HashMap<String, String> properNames = Coordinator.getBibleMapProperNames();
        String fileName = properNames.get(bibleList.getSelectedItem().toString());
        HashMap<String, HashMap> theBible = Coordinator.getTheBible();
        HashMap<Integer, List> theChapters = theBible.get(fileName);
        Set<Integer> keys = theChapters.keySet();
        Integer chosenChapter = Integer.parseInt(chapter.getSelectedItem().toString());
        List<String> verses = theChapters.get(chosenChapter);
        int numberOfVerses = verses.size();
        int verseNumber = Integer.parseInt(verseNumbers.getSelectedItem().toString());
        String selectedVerse = verses.get(verseNumber-1);
 
        
        
        displayBook.append(selectedVerse+"\n\n");
        displayBook.setCaretPosition(0);


    }//GEN-LAST:event_read_verseActionPerformed

    private void read_for_kidsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read_for_kidsActionPerformed
        // TODO add your handling code here:
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gs = ge.getDefaultScreenDevice();
        DisplayMode dm = gs.getDisplayMode();
        int screenWidth = dm.getWidth()-5;
        int screenHeight = dm.getHeight()-5;
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        this.setVisible(true);
        this.setLayout(new BorderLayout());
        this.add(read_next_chapter, BorderLayout.EAST);
        this.add(read_previous_chapter, BorderLayout.WEST);
        this.add(big_letters, BorderLayout.EAST);
        this.add(small_letters, BorderLayout.WEST);
        this.add(displayBook, BorderLayout.CENTER);
        displayBook.setSize(screenWidth, screenHeight);

    }//GEN-LAST:event_read_for_kidsActionPerformed

    private void big_lettersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_big_lettersActionPerformed
        // TODO add your handling code here:
        fontSize = fontSize + 10;
        displayBook.setFont(new java.awt.Font("Dialog", 0, fontSize));
    }//GEN-LAST:event_big_lettersActionPerformed

    private void small_lettersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_small_lettersActionPerformed
        // TODO add your handling code here:
        fontSize = fontSize - 10;
        displayBook.setFont(new java.awt.Font("Dialog", 0, fontSize));
    }//GEN-LAST:event_small_lettersActionPerformed

    private void chapterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chapterActionPerformed
        // TODO add your handling code here:
        displayBook.setText("");
        verseNumbers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        HashMap<String, String> properNames = Coordinator.getBibleMapProperNames();
        String fileName = properNames.get(bibleList.getSelectedItem().toString());
        HashMap<String, HashMap> theBible = Coordinator.getTheBible();
        HashMap<Integer, List> theChapters = theBible.get(fileName);
        Set<Integer> keys = theChapters.keySet();
        Integer chosenChapter = Integer.parseInt(chapter.getSelectedItem().toString());
        List<String> verses = theChapters.get(chosenChapter);
        int numberOfVerses = verses.size();
        for (int i = 1; i<=numberOfVerses; i++)
        {
            verseNumbers.addItem(Integer.toString(i));
        }

 

    }//GEN-LAST:event_chapterActionPerformed

    private void verseNumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verseNumbersActionPerformed
        // TODO add your handling code here:

                

 
       
    }//GEN-LAST:event_verseNumbersActionPerformed

    private void verseNumbersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verseNumbersMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_verseNumbersMouseClicked

    private void read_chapterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read_chapterActionPerformed
        // TODO add your handling code here:
        displayBook.setText("");
        HashMap<String, String> properNames = Coordinator.getBibleMapProperNames();
        String fileName = properNames.get(bibleList.getSelectedItem().toString());
        HashMap<String, HashMap> theBible = Coordinator.getTheBible();
        HashMap<Integer, List> theChapters = theBible.get(fileName);
        Set<Integer> keys = theChapters.keySet();
        Integer chosenChapter = Integer.parseInt(chapter.getSelectedItem().toString());
        List<String> verses = theChapters.get(chosenChapter);
        int numberOfVerses = verses.size();
        for(String verse : verses)
            {
                displayBook.append(verse+"\n\n");
                
            } 
        displayBook.setCaretPosition(0);
    }//GEN-LAST:event_read_chapterActionPerformed

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        // TODO add your handling code here:
        
        String word_to_find = search_word.getText();
                // TODO add your handling code here:
        displayBook.setText("");
        HashMap<String, List> index = Coordinator.getSearchIndex();
        if (index.containsKey(word_to_find)==false)
        {
            JOptionPane.showMessageDialog(null, " no key word in database");
        }
        else
        {
        List<String> indexedWord = index.get(word_to_find);
        int count = 1;
        for (String word : indexedWord)
        {
            //String BookName
            String[] reference = word.split("\\[");
            String fileName = reference[0];
            Integer chapter =  Integer.parseInt(reference[1]);
            Integer verse = Integer.parseInt(reference[2]);
            HashMap<String, HashMap> theBible = Coordinator.getTheBible();
            HashMap<Integer, List> theChapters = theBible.get(fileName);
            Set<Integer> keys = theChapters.keySet();
            Integer chosenChapter = chapter;
            List<String> verses = theChapters.get(chosenChapter);
            displayBook.append(count+") "+properNamesReversed.get(reference[0])+" " + chapter+":"+verse+ "\n" + verses.get(verse-1)+"\n\n");
            count++;
        }
        JOptionPane.showMessageDialog(null, count-1 + " references found");
        }

        displayBook.setCaretPosition(0);
        
        
        
    }//GEN-LAST:event_search_buttonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MainGUI().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Coordinator.buildTheSearchIndex();
        index = Coordinator.getSearchIndex();
        setProperNames();
        JOptionPane.showMessageDialog(null, "building index completed");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         displayBook.setFont(new java.awt.Font("Serif", 0, 300));
                displayBook.setText("");
        HashMap<String, String> properNames = Coordinator.getBibleMapProperNames();
        String fileName = properNames.get(bibleList.getSelectedItem().toString());
        HashMap<String, HashMap> theBible = Coordinator.getTheBible();
        HashMap<Integer, List> theChapters = theBible.get(fileName);
        Set<Integer> keys = theChapters.keySet();
        Integer chosenChapter = Integer.parseInt(chapter.getSelectedItem().toString());
        List<String> verses = theChapters.get(chosenChapter);
        int numberOfVerses = verses.size();
        int verseNumber = Integer.parseInt(verseNumbers.getSelectedItem().toString());
        String selectedVerse = verses.get(verseNumber-1);
        char[] letters = selectedVerse.toCharArray();
        int i = letters.length;
        int[] number = new int[i];
        Random random = new Random();
        char c = selectedVerse.charAt(random.nextInt(selectedVerse.length()));
        String character = Character.toString(c);
        displayBook.setText(character);
        displayBook.setCaretPosition(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KJVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KJVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KJVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KJVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KJVGUI().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bibleList;
    private javax.swing.JButton big_letters;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> chapter;
    private javax.swing.JTextArea displayBook;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JInternalFrame jInternalFrame4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton read_book;
    private javax.swing.JButton read_button;
    private javax.swing.JButton read_button1;
    private javax.swing.JButton read_button5;
    private javax.swing.JButton read_chapter;
    private javax.swing.JButton read_for_kids;
    private javax.swing.JButton read_next_chapter;
    private javax.swing.JButton read_previous_chapter;
    private javax.swing.JButton read_verse;
    private javax.swing.JButton search_button;
    private javax.swing.JTextField search_word;
    private javax.swing.JButton small_letters;
    private javax.swing.JComboBox<String> verseNumbers;
    private javax.swing.JTextArea verseWindow;
    private javax.swing.JScrollPane verseWindow2;
    private javax.swing.JTextArea verseWindow3;
    private javax.swing.JScrollPane verses;
    // End of variables declaration//GEN-END:variables
}
