/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.MathGUI.MathMainGUI;

/**
 *
 * @author giovanni
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form bibleSubject
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        editor = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        science = new javax.swing.JButton();
        math = new javax.swing.JButton();
        stories3 = new javax.swing.JButton();
        stories4 = new javax.swing.JButton();
        stories5 = new javax.swing.JButton();
        stories6 = new javax.swing.JButton();
        stories8 = new javax.swing.JButton();
        stories9 = new javax.swing.JButton();
        stories10 = new javax.swing.JButton();
        stories11 = new javax.swing.JButton();
        stories12 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        stories13 = new javax.swing.JButton();
        stories = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        stories7 = new javax.swing.JButton();

        editor.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        editor.setText("Editor");
        editor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editorActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton3.setText("Songs");

        jButton4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton4.setText("Prophecy");

        science.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        science.setText("Science");
        science.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scienceActionPerformed(evt);
            }
        });

        math.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        math.setText("Maths & Statistics");
        math.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathActionPerformed(evt);
            }
        });

        stories3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        stories3.setText("Languages");
        stories3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stories3ActionPerformed(evt);
            }
        });

        stories4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        stories4.setText("English");
        stories4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stories4ActionPerformed(evt);
            }
        });

        stories5.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        stories5.setText("Technology");
        stories5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stories5ActionPerformed(evt);
            }
        });

        stories6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        stories6.setText("Arts");
        stories6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stories6ActionPerformed(evt);
            }
        });

        stories8.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        stories8.setText("KJV");
        stories8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stories8ActionPerformed(evt);
            }
        });

        stories9.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        stories9.setText("Social Sciences");
        stories9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stories9ActionPerformed(evt);
            }
        });

        stories10.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        stories10.setText("Sabbath");
        stories10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stories10ActionPerformed(evt);
            }
        });

        stories11.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        stories11.setText("Money");
        stories11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stories11ActionPerformed(evt);
            }
        });

        stories12.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        stories12.setText("Marriage");
        stories12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stories12ActionPerformed(evt);
            }
        });

        jButton1.setText("Assessment Records");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        stories13.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        stories13.setText("Ellen G. White");
        stories13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stories13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(stories6, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stories4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(310, 310, 310))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(math, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(stories10, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editor, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(stories11, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(stories5, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(74, 74, 74)
                                        .addComponent(stories8, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(science, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(100, 100, 100))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(stories9, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(stories3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(stories12, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(stories13, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 30, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(math)
                            .addComponent(stories10))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(stories5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stories8)
                                    .addComponent(editor)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stories4)
                    .addComponent(stories6))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(stories11))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(science)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stories9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stories3)
                            .addComponent(stories12, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stories13)))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        stories.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        stories.setText("Stories");
        stories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storiesActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton2.setText("Quizzes");

        stories7.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        stories7.setText("Health & Physical Education");
        stories7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stories7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(stories, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jButton2)))
                        .addGap(38, 38, 38)
                        .addComponent(stories7, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 222, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stories)
                        .addGap(34, 34, 34)
                        .addComponent(jButton2)
                        .addGap(29, 29, 29))
                    .addComponent(stories7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void storiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storiesActionPerformed
        // TODO add your handling code here:
        new StoriesGUI().setVisible(true);
    }//GEN-LAST:event_storiesActionPerformed

    private void editorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editorActionPerformed
        // TODO add your handling code here:
        new EditorGUI().setVisible(true);
    }//GEN-LAST:event_editorActionPerformed

    private void scienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scienceActionPerformed
        // TODO add your handling code here:
        new ScienceGUI().setVisible(true);
        
    }//GEN-LAST:event_scienceActionPerformed

    private void mathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathActionPerformed
        // TODO add your handling code here:
        new MathMainGUI().setVisible(true);
    }//GEN-LAST:event_mathActionPerformed

    private void stories3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stories3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stories3ActionPerformed

    private void stories4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stories4ActionPerformed
        // TODO add your handling code here:
        new EnglishGUI().setVisible(true);
    }//GEN-LAST:event_stories4ActionPerformed

    private void stories5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stories5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stories5ActionPerformed

    private void stories6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stories6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stories6ActionPerformed

    private void stories7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stories7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stories7ActionPerformed

    private void stories8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stories8ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new KJVGUI().setVisible(true);
    }//GEN-LAST:event_stories8ActionPerformed

    private void stories9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stories9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stories9ActionPerformed

    private void stories10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stories10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stories10ActionPerformed

    private void stories11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stories11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stories11ActionPerformed

    private void stories12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stories12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stories12ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new AssessmentRecordGUI().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void stories13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stories13ActionPerformed
        // TODO add your handling code here:
        new EGWGUI().setVisible(true);
    }//GEN-LAST:event_stories13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton math;
    private javax.swing.JButton science;
    private javax.swing.JButton stories;
    private javax.swing.JButton stories10;
    private javax.swing.JButton stories11;
    private javax.swing.JButton stories12;
    private javax.swing.JButton stories13;
    private javax.swing.JButton stories3;
    private javax.swing.JButton stories4;
    private javax.swing.JButton stories5;
    private javax.swing.JButton stories6;
    private javax.swing.JButton stories7;
    private javax.swing.JButton stories8;
    private javax.swing.JButton stories9;
    // End of variables declaration//GEN-END:variables
}
