/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.MathGUI;

import core.Stemmer;
import core.Coordinator;
import java.awt.Color;
import java.util.*;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.awt.image.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.imageio.ImageIO;
import java.awt.Image;
 import java.awt.Font;
import java.awt.Graphics2D;
import core.KJV;
import core.PaintImage;
import java.awt.BorderLayout;
import java.awt.GraphicsEnvironment;
import java.awt.GraphicsDevice;
import java.awt.DisplayMode;

/**
 *
 * @author giovannisaberon
 */
public class CountTwenty extends javax.swing.JFrame {
    List<String> usedWord = new ArrayList();
    HashMap<String, String> images = new HashMap<String, String>();
    HashMap<Integer, String> loopImages = new HashMap<>();
    
    ImageIcon imageIcon;
    String imageDirectory;
    int topNumber;
    int middleNumber;
    int bottomNumber;
    int previousNumber = 0;

    /**
     * Creates new form Math
     */
    
    public CountTwenty() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        question_label = new javax.swing.JLabel();
        item9 = new javax.swing.JLabel();
        item1 = new javax.swing.JLabel();
        middle_image = new javax.swing.JLabel();
        next_button = new javax.swing.JButton();
        item2 = new javax.swing.JLabel();
        item3 = new javax.swing.JLabel();
        item10 = new javax.swing.JLabel();
        item6 = new javax.swing.JLabel();
        item4 = new javax.swing.JLabel();
        item17 = new javax.swing.JLabel();
        item5 = new javax.swing.JLabel();
        item7 = new javax.swing.JLabel();
        item12 = new javax.swing.JLabel();
        item8 = new javax.swing.JLabel();
        item18 = new javax.swing.JLabel();
        item15 = new javax.swing.JLabel();
        item14 = new javax.swing.JLabel();
        item13 = new javax.swing.JLabel();
        item16 = new javax.swing.JLabel();
        item11 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        item19 = new javax.swing.JLabel();
        item20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        question_label.setText("Question");

        next_button.setText("Next");
        next_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_buttonActionPerformed(evt);
            }
        });

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(question_label, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(159, 159, 159)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(item9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(middle_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(item1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(item2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(item10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(82, 82, 82)
                                        .addComponent(item3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(86, 86, 86))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(item13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(item14, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(item15, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(item4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(item6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(item5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(item12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(item7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(item16, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(item17, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(next_button, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(item8, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(item18, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(item19, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(792, 792, 792)
                    .addComponent(item11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(440, 440, 440)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(1251, Short.MAX_VALUE)
                    .addComponent(item20, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(item19, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(447, 447, 447)
                        .addComponent(item18, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(question_label, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(item8, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(next_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(reset)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(item1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(68, 68, 68)
                                        .addComponent(middle_image, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(107, 107, 107)
                                        .addComponent(item3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(item9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(item10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(item13, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(item14, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(item4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(68, 68, 68)
                                        .addComponent(item6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(item2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(174, 174, 174)
                                        .addComponent(item15, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(187, 187, 187)
                                        .addComponent(item16, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(item5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(item7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(item12, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(item17, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(574, Short.MAX_VALUE)
                    .addComponent(item11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(151, 151, 151)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(547, Short.MAX_VALUE)
                    .addComponent(item20, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(154, 154, 154)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void next_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_buttonActionPerformed
        // TODO add your handling code here:
        images = new HashMap<>();
        imageDirectory = "fruit_pics";
        images =Coordinator.ScienceGetImages("/resources/images/science/"+imageDirectory);   
        System.out.println(images.size());
        Set<String> imageKey = images.keySet();
        loopImages = new HashMap<>();        
        int loopCount = 0;
        for (String key : imageKey)
        {            
            loopImages.put(loopCount, images.get(key));
            loopCount++;
        } 
        generateItems();
        Random randomQuestion = new Random();
        ArrayList questions = new ArrayList();
        questions.add("What is at the top?");
        questions.add("What is in the middle?");
        questions.add("What is at the bottom?");       
        int randomNumber = randomQuestion.nextInt(questions.size());
        while (randomNumber==previousNumber)
        {
            randomNumber = randomQuestion.nextInt(questions.size());
        }
        String selectedQuestion = questions.get(randomNumber).toString();       
        question_label.setText(selectedQuestion);
        previousNumber = randomNumber;
        question_label.setFont(new java.awt.Font("Dialog", 0, 30));
        
    }//GEN-LAST:event_next_buttonActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
                        item1.setVisible(false);
        item2.setVisible(false);
        item3.setVisible(false);
        item4.setVisible(false);
        item5.setVisible(false);
        item6.setVisible(false);
        item7.setVisible(false);
        item8.setVisible(false);
        item9.setVisible(false);
        item10.setVisible(false);
                item11.setVisible(false);
                item12.setVisible(false);
        item13.setVisible(false);
        item14.setVisible(false);
        item15.setVisible(false);
        item16.setVisible(false);
        item17.setVisible(false);
        item18.setVisible(false);
        item19.setVisible(false);
        item20.setVisible(false);
    }//GEN-LAST:event_resetActionPerformed

        private void generateItems()
    {


        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gs = ge.getDefaultScreenDevice();
        DisplayMode dm = gs.getDisplayMode();
        int screenWidth = dm.getWidth()-5;
        int screenHeight = dm.getHeight()-5;
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        this.setVisible(true);
        this.setLayout(new BorderLayout());
           Random randomTop = new Random();
        topNumber = randomTop.nextInt(images.size());
        while (topNumber>8)
        {
        topNumber = randomTop.nextInt(images.size());
        }

            String imageFileName = loopImages.get(topNumber);
            String[] imageName = imageFileName.split("\\.");
            imageIcon = new javax.swing.ImageIcon(getClass().getResource("/resources/images/science/"+imageDirectory+"/"+imageFileName));
            int height = item1.getHeight();
            int width = item1.getWidth();
            //get the image
            Image image = imageIcon.getImage();
            //transform it
            Image newimg = image.getScaledInstance(height-5, width-5,  java.awt.Image.SCALE_SMOOTH);
            //get the new image
            imageIcon = new ImageIcon(newimg);
        Random randomItemNumber = new Random();
        int itemNumber = randomTop.nextInt(20)+1;
        int numberOfItems = itemNumber;
        
        if (numberOfItems == 1)
        {
             

            item1.setIcon(imageIcon);  
            item1.setVisible(true);
 
            

        }
        if (numberOfItems == 2)
        {

            item1.setIcon(imageIcon);  
            item2.setIcon(imageIcon);  
            item1.setVisible(true);
            item2.setVisible(true);
  
            

        }
        if (numberOfItems == 3)
        {

            item1.setIcon(imageIcon);  
            item2.setIcon(imageIcon);  
            item3.setIcon(imageIcon);  
            item1.setVisible(true);
            item2.setVisible(true);
            item3.setVisible(true);

 
            

        }
        if (numberOfItems == 4)
        {

            item1.setIcon(imageIcon);  
            item2.setIcon(imageIcon);  
            item3.setIcon(imageIcon);  
            item4.setIcon(imageIcon);  
            item1.setVisible(true);
            item2.setVisible(true);
            item3.setVisible(true);
             item4.setVisible(true);

            

        }
        if (numberOfItems == 5)
        {

            item1.setIcon(imageIcon);  
            item2.setIcon(imageIcon);  
            item3.setIcon(imageIcon);  
            item4.setIcon(imageIcon);  
            item5.setIcon(imageIcon);  
           item1.setVisible(true);
            item2.setVisible(true);
            item3.setVisible(true);
             item4.setVisible(true);
               item5.setVisible(true);

            

        }
        if (numberOfItems == 6)
        {

            item1.setIcon(imageIcon);  
            item2.setIcon(imageIcon);  
            item3.setIcon(imageIcon);  
            item4.setIcon(imageIcon);  
            item5.setIcon(imageIcon);  
            item6.setIcon(imageIcon);  
                     item1.setVisible(true);
            item2.setVisible(true);
            item3.setVisible(true);
             item4.setVisible(true);
               item5.setVisible(true);
                item6.setVisible(true);

            

        }
        if (numberOfItems == 7)
        {

            item1.setIcon(imageIcon);  
            item2.setIcon(imageIcon);  
            item3.setIcon(imageIcon);  
            item4.setIcon(imageIcon);  
            item5.setIcon(imageIcon);  
            item6.setIcon(imageIcon);  
            item7.setIcon(imageIcon);  
                                 item1.setVisible(true);
            item2.setVisible(true);
            item3.setVisible(true);
             item4.setVisible(true);
               item5.setVisible(true);
                item6.setVisible(true);
                 item7.setVisible(true);
            

        }
        if (numberOfItems == 8)
        {

            item1.setIcon(imageIcon);  
            item2.setIcon(imageIcon);  
            item3.setIcon(imageIcon);  
            item4.setIcon(imageIcon);  
            item5.setIcon(imageIcon);  
            item6.setIcon(imageIcon);  
            item7.setIcon(imageIcon);  
           item1.setVisible(true);
            item2.setVisible(true);
            item3.setVisible(true);
             item4.setVisible(true);
               item5.setVisible(true);
                item6.setVisible(true);
                 item7.setVisible(true);

                item8.setVisible(true);

        }
        if (numberOfItems == 9)
        {

            item1.setIcon(imageIcon);  
            item2.setIcon(imageIcon);  
            item3.setIcon(imageIcon);  
            item4.setIcon(imageIcon);  
            item5.setIcon(imageIcon);  
            item6.setIcon(imageIcon);  
            item7.setIcon(imageIcon);  
            item8.setIcon(imageIcon);  
            item9.setIcon(imageIcon);  
              item1.setVisible(true);
            item2.setVisible(true);
            item3.setVisible(true);
             item4.setVisible(true);
               item5.setVisible(true);
                item6.setVisible(true);
                 item7.setVisible(true);

                item8.setVisible(true);
                         item9.setVisible(true);
            

        }
        if (numberOfItems == 10)
        {

            item1.setIcon(imageIcon);  
            item2.setIcon(imageIcon);  
            item3.setIcon(imageIcon);  
            item4.setIcon(imageIcon);  
            item5.setIcon(imageIcon);  
            item6.setIcon(imageIcon);  
            item7.setIcon(imageIcon);  
            item8.setIcon(imageIcon);  
            item9.setIcon(imageIcon);  
            item10.setIcon(imageIcon);  
                        item1.setVisible(true);
            item2.setVisible(true);
            item3.setVisible(true);
             item4.setVisible(true);
               item5.setVisible(true);
                item6.setVisible(true);
                 item7.setVisible(true);

                item8.setVisible(true);
                         item9.setVisible(true);
             item10.setVisible(true);

        }
        if (numberOfItems == 11)
        {

            item1.setIcon(imageIcon);  
            item2.setIcon(imageIcon);  
            item3.setIcon(imageIcon);  
            item4.setIcon(imageIcon);  
            item5.setIcon(imageIcon);  
            item6.setIcon(imageIcon);  
            item7.setIcon(imageIcon);  
            item8.setIcon(imageIcon);  
            item9.setIcon(imageIcon);  
            item10.setIcon(imageIcon);  
             item11.setIcon(imageIcon);  
                        item1.setVisible(true);
            item2.setVisible(true);
            item3.setVisible(true);
             item4.setVisible(true);
               item5.setVisible(true);
                item6.setVisible(true);
                 item7.setVisible(true);

                item8.setVisible(true);
                         item9.setVisible(true);
             item10.setVisible(true);
             item11.setVisible(true);

        }     
                if (numberOfItems == 12)
        {

            item1.setIcon(imageIcon);  
            item2.setIcon(imageIcon);  
            item3.setIcon(imageIcon);  
            item4.setIcon(imageIcon);  
            item5.setIcon(imageIcon);  
            item6.setIcon(imageIcon);  
            item7.setIcon(imageIcon);  
            item8.setIcon(imageIcon);  
            item9.setIcon(imageIcon);  
            item10.setIcon(imageIcon);  
             item11.setIcon(imageIcon);  
             item12.setIcon(imageIcon);  
                        item1.setVisible(true);
            item2.setVisible(true);
            item3.setVisible(true);
             item4.setVisible(true);
               item5.setVisible(true);
                item6.setVisible(true);
                 item7.setVisible(true);

                item8.setVisible(true);
                         item9.setVisible(true);
             item10.setVisible(true);
             item11.setVisible(true);
                item12.setVisible(true);

        }  
                                if (numberOfItems == 13)
        {

            item1.setIcon(imageIcon);  
            item2.setIcon(imageIcon);  
            item3.setIcon(imageIcon);  
            item4.setIcon(imageIcon);  
            item5.setIcon(imageIcon);  
            item6.setIcon(imageIcon);  
            item7.setIcon(imageIcon);  
            item8.setIcon(imageIcon);  
            item9.setIcon(imageIcon);  
            item10.setIcon(imageIcon);  
             item11.setIcon(imageIcon);  
             item12.setIcon(imageIcon);  
               item13.setIcon(imageIcon);  
                        item1.setVisible(true);
            item2.setVisible(true);
            item3.setVisible(true);
             item4.setVisible(true);
               item5.setVisible(true);
                item6.setVisible(true);
                 item7.setVisible(true);

                item8.setVisible(true);
                         item9.setVisible(true);
             item10.setVisible(true);
             item11.setVisible(true);
                item12.setVisible(true);
                item13.setVisible(true);

        }  
                                if (numberOfItems == 14)
        {

            item1.setIcon(imageIcon);  
            item2.setIcon(imageIcon);  
            item3.setIcon(imageIcon);  
            item4.setIcon(imageIcon);  
            item5.setIcon(imageIcon);  
            item6.setIcon(imageIcon);  
            item7.setIcon(imageIcon);  
            item8.setIcon(imageIcon);  
            item9.setIcon(imageIcon);  
            item10.setIcon(imageIcon);  
             item11.setIcon(imageIcon);  
             item12.setIcon(imageIcon);  
               item13.setIcon(imageIcon); 
               item14.setIcon(imageIcon); 
                        item1.setVisible(true);
            item2.setVisible(true);
            item3.setVisible(true);
             item4.setVisible(true);
               item5.setVisible(true);
                item6.setVisible(true);
                 item7.setVisible(true);

                item8.setVisible(true);
                         item9.setVisible(true);
             item10.setVisible(true);
             item11.setVisible(true);
                item12.setVisible(true);
                item13.setVisible(true);
                item14.setVisible(true);

        }       
        if (numberOfItems == 15)
        {

            item1.setIcon(imageIcon);  
            item2.setIcon(imageIcon);  
            item3.setIcon(imageIcon);  
            item4.setIcon(imageIcon);  
            item5.setIcon(imageIcon);  
            item6.setIcon(imageIcon);  
            item7.setIcon(imageIcon);  
            item8.setIcon(imageIcon);  
            item9.setIcon(imageIcon);  
            item10.setIcon(imageIcon);  
             item11.setIcon(imageIcon);  
             item12.setIcon(imageIcon);  
               item13.setIcon(imageIcon); 
               item14.setIcon(imageIcon); 
                item15.setIcon(imageIcon); 
                        item1.setVisible(true);
            item2.setVisible(true);
            item3.setVisible(true);
             item4.setVisible(true);
               item5.setVisible(true);
                item6.setVisible(true);
                 item7.setVisible(true);

                item8.setVisible(true);
                         item9.setVisible(true);
             item10.setVisible(true);
             item11.setVisible(true);
                item12.setVisible(true);
                item13.setVisible(true);
                item14.setVisible(true);
                item15.setVisible(true);

        } 
                if (numberOfItems == 16)
        {

            item1.setIcon(imageIcon);  
            item2.setIcon(imageIcon);  
            item3.setIcon(imageIcon);  
            item4.setIcon(imageIcon);  
            item5.setIcon(imageIcon);  
            item6.setIcon(imageIcon);  
            item7.setIcon(imageIcon);  
            item8.setIcon(imageIcon);  
            item9.setIcon(imageIcon);  
            item10.setIcon(imageIcon);  
             item11.setIcon(imageIcon);  
             item12.setIcon(imageIcon);  
               item13.setIcon(imageIcon); 
               item14.setIcon(imageIcon); 
                item15.setIcon(imageIcon); 
                 item16.setIcon(imageIcon); 
                        item1.setVisible(true);
            item2.setVisible(true);
            item3.setVisible(true);
             item4.setVisible(true);
               item5.setVisible(true);
                item6.setVisible(true);
                 item7.setVisible(true);

                item8.setVisible(true);
                         item9.setVisible(true);
             item10.setVisible(true);
             item11.setVisible(true);
                item12.setVisible(true);
                item13.setVisible(true);
                item14.setVisible(true);
                item15.setVisible(true);
                    item16.setVisible(true);

        } 
                                if (numberOfItems == 17)
        {

            item1.setIcon(imageIcon);  
            item2.setIcon(imageIcon);  
            item3.setIcon(imageIcon);  
            item4.setIcon(imageIcon);  
            item5.setIcon(imageIcon);  
            item6.setIcon(imageIcon);  
            item7.setIcon(imageIcon);  
            item8.setIcon(imageIcon);  
            item9.setIcon(imageIcon);  
            item10.setIcon(imageIcon);  
             item11.setIcon(imageIcon);  
             item12.setIcon(imageIcon);  
               item13.setIcon(imageIcon); 
               item14.setIcon(imageIcon); 
                item15.setIcon(imageIcon); 
                 item16.setIcon(imageIcon); 
                 item17.setIcon(imageIcon);
                        item1.setVisible(true);
            item2.setVisible(true);
            item3.setVisible(true);
             item4.setVisible(true);
               item5.setVisible(true);
                item6.setVisible(true);
                 item7.setVisible(true);

                item8.setVisible(true);
                         item9.setVisible(true);
             item10.setVisible(true);
             item11.setVisible(true);
                item12.setVisible(true);
                item13.setVisible(true);
                item14.setVisible(true);
                item15.setVisible(true);
                    item16.setVisible(true);
                     item17.setVisible(true);

        } 
if (numberOfItems == 18)
        {

            item1.setIcon(imageIcon);  
            item2.setIcon(imageIcon);  
            item3.setIcon(imageIcon);  
            item4.setIcon(imageIcon);  
            item5.setIcon(imageIcon);  
            item6.setIcon(imageIcon);  
            item7.setIcon(imageIcon);  
            item8.setIcon(imageIcon);  
            item9.setIcon(imageIcon);  
            item10.setIcon(imageIcon);  
             item11.setIcon(imageIcon);  
             item12.setIcon(imageIcon);  
               item13.setIcon(imageIcon); 
               item14.setIcon(imageIcon); 
                item15.setIcon(imageIcon); 
                 item16.setIcon(imageIcon); 
                 item17.setIcon(imageIcon);
                   item18.setIcon(imageIcon);
                        item1.setVisible(true);
            item2.setVisible(true);
            item3.setVisible(true);
             item4.setVisible(true);
               item5.setVisible(true);
                item6.setVisible(true);
                 item7.setVisible(true);

                item8.setVisible(true);
                         item9.setVisible(true);
             item10.setVisible(true);
             item11.setVisible(true);
                item12.setVisible(true);
                item13.setVisible(true);
                item14.setVisible(true);
                item15.setVisible(true);
                    item16.setVisible(true);
                     item17.setVisible(true);
                       item18.setVisible(true);

        } 
if (numberOfItems == 19)
        {

            item1.setIcon(imageIcon);  
            item2.setIcon(imageIcon);  
            item3.setIcon(imageIcon);  
            item4.setIcon(imageIcon);  
            item5.setIcon(imageIcon);  
            item6.setIcon(imageIcon);  
            item7.setIcon(imageIcon);  
            item8.setIcon(imageIcon);  
            item9.setIcon(imageIcon);  
            item10.setIcon(imageIcon);  
             item11.setIcon(imageIcon);  
             item12.setIcon(imageIcon);  
               item13.setIcon(imageIcon); 
               item14.setIcon(imageIcon); 
                item15.setIcon(imageIcon); 
                 item16.setIcon(imageIcon); 
                 item17.setIcon(imageIcon);
                   item18.setIcon(imageIcon);
                    item19.setIcon(imageIcon);
                        item1.setVisible(true);
            item2.setVisible(true);
            item3.setVisible(true);
             item4.setVisible(true);
               item5.setVisible(true);
                item6.setVisible(true);
                 item7.setVisible(true);

                item8.setVisible(true);
                         item9.setVisible(true);
             item10.setVisible(true);
             item11.setVisible(true);
                item12.setVisible(true);
                item13.setVisible(true);
                item14.setVisible(true);
                item15.setVisible(true);
                    item16.setVisible(true);
                     item17.setVisible(true);
                       item18.setVisible(true);
                       item19.setVisible(true);

        } 
 if (numberOfItems == 20)
        {

            item1.setIcon(imageIcon);  
            item2.setIcon(imageIcon);  
            item3.setIcon(imageIcon);  
            item4.setIcon(imageIcon);  
            item5.setIcon(imageIcon);  
            item6.setIcon(imageIcon);  
            item7.setIcon(imageIcon);  
            item8.setIcon(imageIcon);  
            item9.setIcon(imageIcon);  
            item10.setIcon(imageIcon);  
             item11.setIcon(imageIcon);  
             item12.setIcon(imageIcon);  
               item13.setIcon(imageIcon); 
               item14.setIcon(imageIcon); 
                item15.setIcon(imageIcon); 
                 item16.setIcon(imageIcon); 
                 item17.setIcon(imageIcon);
                   item18.setIcon(imageIcon);
                    item19.setIcon(imageIcon);
                     item20.setIcon(imageIcon);
                        item1.setVisible(true);
            item2.setVisible(true);
            item3.setVisible(true);
             item4.setVisible(true);
               item5.setVisible(true);
                item6.setVisible(true);
                 item7.setVisible(true);

                item8.setVisible(true);
                         item9.setVisible(true);
             item10.setVisible(true);
             item11.setVisible(true);
                item12.setVisible(true);
                item13.setVisible(true);
                item14.setVisible(true);
                item15.setVisible(true);
                    item16.setVisible(true);
                     item17.setVisible(true);
                       item18.setVisible(true);
                       item19.setVisible(true);
                        item20.setVisible(true);

        }           
            
    }
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CountTwenty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CountTwenty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CountTwenty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CountTwenty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CountTwenty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel item1;
    private javax.swing.JLabel item10;
    private javax.swing.JLabel item11;
    private javax.swing.JLabel item12;
    private javax.swing.JLabel item13;
    private javax.swing.JLabel item14;
    private javax.swing.JLabel item15;
    private javax.swing.JLabel item16;
    private javax.swing.JLabel item17;
    private javax.swing.JLabel item18;
    private javax.swing.JLabel item19;
    private javax.swing.JLabel item2;
    private javax.swing.JLabel item20;
    private javax.swing.JLabel item3;
    private javax.swing.JLabel item4;
    private javax.swing.JLabel item5;
    private javax.swing.JLabel item6;
    private javax.swing.JLabel item7;
    private javax.swing.JLabel item8;
    private javax.swing.JLabel item9;
    private javax.swing.JLabel middle_image;
    private javax.swing.JButton next_button;
    private javax.swing.JLabel question_label;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
