/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.MathGUI;
import gui.MathGUI.TopMiddleBottom;
import gui.MathGUI.LeftMiddleRight;
import core.Stemmer;
import core.Coordinator;
import java.awt.Color;
import java.util.*;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.awt.image.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.imageio.ImageIO;
import java.awt.Image;
 import java.awt.Font;
import java.awt.Graphics2D;
import core.KJV;
import java.awt.BorderLayout;
import java.awt.GraphicsEnvironment;
import java.awt.GraphicsDevice;
import java.awt.DisplayMode;
import java.awt.image.*; 
import javax.imageio.*; 
import java.awt.Graphics; 

/**
 *
 * @author giovannisaberon
 */
public class MathMainGUI extends javax.swing.JFrame {
    List<String> usedWord = new ArrayList();
    HashMap<String, String> images = new HashMap<String, String>();
    HashMap<Integer, String> loopImages = new HashMap<>();
    ImageIcon imageIcon;
    String imageDirectory;
    int topNumber;
    int middleNumber;
    int bottomNumber;
    int previousNumber = 0;
    

    /**
     * Creates new form Math
     */
    
    public MathMainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topMiddleBottom = new javax.swing.JButton();
        leftMiddleRight = new javax.swing.JButton();
        besideNextTo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        topMiddleBottom.setText("Top, Middle, Bottom");
        topMiddleBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topMiddleBottomActionPerformed(evt);
            }
        });

        leftMiddleRight.setText("Left, Middle, Right");
        leftMiddleRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftMiddleRightActionPerformed(evt);
            }
        });

        besideNextTo.setText("Beside, Next To");
        besideNextTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                besideNextToActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(besideNextTo)
                    .addComponent(topMiddleBottom)
                    .addComponent(leftMiddleRight, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1057, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(topMiddleBottom)
                .addGap(27, 27, 27)
                .addComponent(leftMiddleRight)
                .addGap(41, 41, 41)
                .addComponent(besideNextTo)
                .addContainerGap(647, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
  
  
    private void topMiddleBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topMiddleBottomActionPerformed
        // TODO add your handling code here:
        new TopMiddleBottom().setVisible(true);
    }//GEN-LAST:event_topMiddleBottomActionPerformed

    private void leftMiddleRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftMiddleRightActionPerformed
        // TODO add your handling code here:
        new LeftMiddleRight().setVisible(true);
    }//GEN-LAST:event_leftMiddleRightActionPerformed

    private void besideNextToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_besideNextToActionPerformed
        // TODO add your handling code here:
        new  BesideNextTo().setVisible(true);
    }//GEN-LAST:event_besideNextToActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MathMainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton besideNextTo;
    private javax.swing.JButton leftMiddleRight;
    private javax.swing.JButton topMiddleBottom;
    // End of variables declaration//GEN-END:variables
}
