/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.MathGUI;

import core.Stemmer;
import core.Coordinator;
import java.awt.Color;
import java.util.*;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.awt.image.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.imageio.ImageIO;
import java.awt.Image;
 import java.awt.Font;
import java.awt.Graphics2D;
import core.KJV;
import java.awt.BorderLayout;
import java.awt.GraphicsEnvironment;
import java.awt.GraphicsDevice;
import java.awt.DisplayMode;

/**
 *
 * @author giovannisaberon
 */
public class TopMiddleBottom extends javax.swing.JFrame {
    List<String> usedWord = new ArrayList();
    HashMap<String, String> images = new HashMap<String, String>();
    HashMap<Integer, String> loopImages = new HashMap<>();
    ImageIcon imageIcon;
    String imageDirectory;
    int topNumber;
    int middleNumber;
    int bottomNumber;
    int previousNumber = 0;

    /**
     * Creates new form Math
     */
    
    public TopMiddleBottom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        question_label = new javax.swing.JLabel();
        bottom_image = new javax.swing.JLabel();
        top_image = new javax.swing.JLabel();
        middle_image = new javax.swing.JLabel();
        next_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        question_label.setText("Question");

        bottom_image.setText("jLabel2");

        top_image.setText("jLabel2");

        middle_image.setText("jLabel2");

        next_button.setText("Next");
        next_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(top_image, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(middle_image, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bottom_image, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(236, 236, 236))
                    .addComponent(question_label, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(next_button, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(345, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(question_label, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(top_image, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(next_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(middle_image, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bottom_image, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void next_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_buttonActionPerformed
        // TODO add your handling code here:
        images = new HashMap<>();
        imageDirectory = "fruit_pics";
        images =Coordinator.ScienceGetImages("/resources/images/science/"+imageDirectory);   
        System.out.println(images.size());
        Set<String> imageKey = images.keySet();
        loopImages = new HashMap<>();        
        int loopCount = 0;
        for (String key : imageKey)
        {            
            loopImages.put(loopCount, images.get(key));
            loopCount++;
        } 
        
        setTopImage();
        setMiddleImage();
        setBottomImage();
        Random randomQuestion = new Random();
        ArrayList questions = new ArrayList();
        questions.add("What is at the top?");
        questions.add("What is in the middle?");
        questions.add("What is at the bottom?");       
        int randomNumber = randomQuestion.nextInt(questions.size());
        while (randomNumber==previousNumber)
        {
            randomNumber = randomQuestion.nextInt(questions.size());
        }
        String selectedQuestion = questions.get(randomNumber).toString();       
        question_label.setText(selectedQuestion);
        previousNumber = randomNumber;
        question_label.setFont(new java.awt.Font("Dialog", 0, 30));
        
    }//GEN-LAST:event_next_buttonActionPerformed

        private void setTopImage()
    {

           Random randomTop = new Random();
        topNumber = randomTop.nextInt(images.size());
        while (topNumber>8)
        {
        topNumber = randomTop.nextInt(images.size());
        }
        System.out.println(topNumber);

            String imageFileName = loopImages.get(topNumber);
            String[] imageName = imageFileName.split("\\.");
            imageIcon = new javax.swing.ImageIcon(getClass().getResource("/resources/images/science/"+imageDirectory+"/"+imageFileName));
            int height = top_image.getHeight();
            int width = top_image.getWidth();
            //get the image
            Image image = imageIcon.getImage();
            //transform it
            Image newimg = image.getScaledInstance(height-5, width-5,  java.awt.Image.SCALE_SMOOTH);
            //get the new image
            imageIcon = new ImageIcon(newimg);
            top_image.setIcon(imageIcon);    
            
    }
    private void setMiddleImage()
    {
        Random randomMiddle = new Random();
        middleNumber = randomMiddle.nextInt(loopImages.size());
        while (middleNumber==topNumber || middleNumber>10)
        {
            middleNumber = randomMiddle.nextInt(loopImages.size());
        }
        System.out.println(middleNumber);
            String imageFileName = loopImages.get(middleNumber);
            String[] imageName = imageFileName.split("\\.");
            imageIcon = new javax.swing.ImageIcon(getClass().getResource("/resources/images/science/"+imageDirectory+"/"+imageFileName));
            int height = top_image.getHeight();
            int width = top_image.getWidth();
            //get the image
            Image image = imageIcon.getImage();
            //transform it
            Image newimg = image.getScaledInstance(height-5, width-5,  java.awt.Image.SCALE_SMOOTH);
            //get the new image
            imageIcon = new ImageIcon(newimg);
            middle_image.setIcon(imageIcon);   
    }
    
    private void setBottomImage()
    {
        Random randomBottom = new Random();
        bottomNumber = randomBottom.nextInt(loopImages.size());
        while (bottomNumber==topNumber || bottomNumber>10 || bottomNumber==middleNumber)
        {
            bottomNumber = randomBottom.nextInt(loopImages.size());
        }
        System.out.println(bottomNumber);
            String imageFileName = loopImages.get(bottomNumber);
            String[] imageName = imageFileName.split("\\.");
            imageIcon = new javax.swing.ImageIcon(getClass().getResource("/resources/images/science/"+imageDirectory+"/"+imageFileName));
            int height = top_image.getHeight();
            int width = top_image.getWidth();
            //get the image
            Image image = imageIcon.getImage();
            //transform it
            Image newimg = image.getScaledInstance(height-5, width-5,  java.awt.Image.SCALE_SMOOTH);
            //get the new image
            imageIcon = new ImageIcon(newimg);
            bottom_image.setIcon(imageIcon);   
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TopMiddleBottom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TopMiddleBottom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TopMiddleBottom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TopMiddleBottom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TopMiddleBottom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bottom_image;
    private javax.swing.JLabel middle_image;
    private javax.swing.JButton next_button;
    private javax.swing.JLabel question_label;
    private javax.swing.JLabel top_image;
    // End of variables declaration//GEN-END:variables
}
